version: '3'
services:
  mongodb:
    container_name: diplom_2_mongodb_1
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
    networks:
      - network1
  server:
    build: server
    env_file: 
      - server/.env
    ports: 
      - 8000:8000
    networks:
      - network1

networks:
  network1:
    driver: bridge